FROM ubuntu:12.04

# Because there is no package cache in the image, you need to run:
RUN apt-get update

# Install nodejs 
RUN apt-get -y install software-properties-common python-software-properties bzip2
RUN apt-add-repository ppa:chris-lea/node.js
RUN apt-get update
RUN apt-get install -y nodejs

RUN npm install tty-table

# Install grunt
RUN npm install grunt-cli -g

# Install dev dependencies
WORKDIR /node_modules/tty-table
RUN npm install

# Run unit tests
RUN grunt t
