FROM centos:7

RUN yum install -y epel-release

# Install bzip2 
RUN yum install -y bzip2

RUN yum install -y git

# Install nodejs 8 
RUN curl -sL https://rpm.nodesource.com/setup_12.x | bash -
RUN yum install -y nodejs

# RUN ln -s /usr/bin/nodejs /usr/bin/node

# Install tty-table
RUN git clone https://www.github.com/tecfu/tty-table

# Install dev dependencies
WORKDIR /tty-table
RUN npm install

# Run unit tests
RUN npx mocha
