FROM centos:7

RUN yum install -y epel-release

# Install nodejs 
RUN yum install -y nodejs npm
# RUN ln -s /usr/bin/nodejs /usr/bin/node
# Install bzip2 
RUN yum install -y bzip2

# Install tty-table
RUN npm install tty-table

# Install grunt
RUN npm install grunt-cli -g

# Install dev dependencies
WORKDIR /node_modules/tty-table
ADD . /node_modules/tty-table
RUN npm install

# Run unit tests
RUN grunt t
