FROM ubuntu:12.04.5

# Because there is no package cache in the image, you need to run:
RUN apt-get update

# Install nodejs 
RUN apt-get -y install software-properties-common python-software-properties bzip2
RUN apt-add-repository ppa:chris-lea/node.js
RUN apt-get update
RUN apt-get install -y nodejs

# Install tty-table
RUN apt-get install git -y
RUN git clone https://www.github.com/tecfu/tty-table

# Install grunt
RUN npm install grunt-cli -g

# Install dev dependencies
WORKDIR /tty-table
RUN npm install

# Run unit tests
RUN grunt t
